apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
  labels:
    app: postgres
data:
  postgres_db: postgres
  db_url: postgresql://postgres:postgres@postgres:5432/postgres
  migration: "TRUE"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
    postgres_user: cG9zdGdyZXM=
    postgres_password: cG9zdGdyZXM=
---
apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
  namespace: student-api
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIllXRnphR2x5WVhSb2IzSmxNVEV4T2tsaVpIQnBkRFl6TmpJNE1DRT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
    