{
 "title": "Host Resources Usage",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "BlackBox-Exporter-Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "probe_http_status_code", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (cpu) (irate(node_cpu_seconds_total [1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk-usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - 100 * (node_filesystem_avail_bytes) / (node_filesystem_size_bytes)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Application-Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{container=\"flask-app\"} |= ``"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Cached_bytes - node_memory_Buffers_bytes",
     "legendFormat": "used"
    },
    { "expr": "node_memory_Buffers_bytes", "legendFormat": "buffer" },
    { "expr": "node_memory_Cached_bytes", "legendFormat": "cache" },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "memFree" }
   ]
  },
  {
   "title": "Kube-State-Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    { "expr": "kube_pod_created", "legendFormat": "pods" },
    { "expr": "kube_node_created", "legendFormat": "nodes" }
   ]
  },
  {
   "title": "DB-Metrics",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "pg_stat_database_stats_reset", "legendFormat": "__auto" }
   ]
  }
 ]
}