apiVersion: {{ .Values.apiVersion | default "v1" }}
kind: ConfigMap
metadata:
  name: app-configmap
  namespace: {{.Values.namespace.getns}}
  labels:
    app: postgres
data:
  postgres_db: postgres
  migration: "TRUE"
  flask_run_host: 0.0.0.0