apiVersion: {{ .Values.apiVersion | default "v1" }}
kind: Secret
metadata:
  name: myregistrykey
  namespace: {{.Values.namespace.getns}}
data:
  .dockercfg: {{.Values.secret.auth}}
type: kubernetes.io/dockercfg
---
apiVersion: {{ .Values.apiVersion | default "v1" }}
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{.Values.namespace.getns}}
type: {{ .Values.secret.type}}
data:
    postgres_user: {{ .Values.secret.user | b64enc }}
    postgres_password: {{ .Values.secret.password  | b64enc}}
    db_url: {{ .Values.secret.dburl | b64enc }}