apiVersion: {{ .Values.apiVersion | default "v1" }}
kind: Service
metadata:
  name: postgres
  namespace: {{.Values.namespace.getns}}
  labels:
    {{- include "mydb.labels" .}}
spec:
  ports:
  - port: 5432
    name: postgresdb
  clusterIP: None
  selector:
    app: postgres
---
apiVersion: {{ .Values.apiVersion | default "v1" }}
kind: Service
metadata:
  name: student-api-service
  namespace: {{.Values.namespace.getns}}
  labels:
    {{- include "mycharts.labels" .}}
spec:
    ports:
    - port: {{.Values.service.port}}
      protocol: TCP
      targetPort: {{.Values.service.targetPort}}
    selector:
      {{- include "mycharts.labels" .}}
    type: {{.Values.service.type}}