apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-ns
  namespace: student-api
spec:
  rules:
    - host: student.api.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: student-api-service
                port:
                  number: 5000