"""empty message

Revision ID: 3de6a45100d5
Revises: abd4d57800f2
Create Date: 2024-03-18 18:48:53.184342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de6a45100d5'
down_revision = 'abd4d57800f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('rollno',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['rollno'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('rollno',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
