"""empty message

Revision ID: b41a06a7984c
Revises: 
Create Date: 2024-03-19 12:16:18.198180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b41a06a7984c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rollnew', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['rollnew'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('rollnew')

    # ### end Alembic commands ###
