"""empty message

Revision ID: edaec46567fc
Revises: 2f335f816329
Create Date: 2024-03-19 16:24:50.271801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edaec46567fc'
down_revision = '2f335f816329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rollno', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['rollno'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('rollno')

    # ### end Alembic commands ###
