name: GitHub Actions CI/CD
run-name: Deploying Local CI.
on:
  push:
    branches:
      - exercise-05
jobs:
  CD:
    runs-on: self-hosted
    steps:
      - run: echo "The job was automatically triggered by a Push event."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."

      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up SSH key and Trigger deployment
        env:
          VAGRANT_SSH_KEY: ${{ secrets.VAGRANT_SSH_KEY }}
        run: |
          echo "$VAGRANT_SSH_KEY" | tr -d '\r' > id_rsa
          chmod 0400 id_rsa
          ssh-add id_rsa
          ls