name: GitHub Actions CI/CD
run-name: Local CI/CD.
on:
  push:
    branches:
     - exercise-05
jobs:
  CI:
    runs-on: self-hosted
    steps:
      - run: echo "The job was automatically triggered by a Push event."
     
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      
      - name: Get Hash
        id: get_commit_hash
        run: echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")"

      - name: Export commit id.
        run: |
          export SHORT_COMMIT_HASH=${{ steps.get_commit_hash.outputs.hash }}
          echo "Stage export completed."

      - name: Building flask application.
        run: |
          make docker-build
        env:
          IMAGE_TAG: "${{ env.hash }}"

      - name: Run docker build.
        run: |
          make start-db

      - name: Push the Image into dockerHub.
        run: |
          make docker_push
        env:
          USERNAME: ${{secrets.DOCKER_USERNAME}}
          IMAGE_TAG: ${{ env.hash }}
  CD:
    runs-on: self-hosted
    steps:
      - name: Get short SHA
        run: echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")"

      - name: Set up SSH key and Trigger deployment.
        env:
          VAGRANT_SSH_KEY: ${{ secrets.VAGRANT_SSH_KEY }}
          IMAGE_TAG: ${{ env.hash }}
        run: |
          rm /tmp/id_rsa
          echo "$VAGRANT_SSH_KEY" | tr -d '\r' > /tmp/id_rsa
          chmod 0400 /tmp/id_rsa
          ssh -i /tmp/id_rsa -p 2222 vagrant@127.0.0.1 ls -l