name: GitHub Actions CI/CD
run-name: Deploying Local CI and Local CD.
on:
  push:
    branches:
      - exercise-04
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a Push event."
     
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Run flask application.
        run: |
          make flaskapp_build
      - name: Run docker compose.
        run: |
          make docker_build
      # - name: Push the Image in dockerHub.
      #   run: |
      #    ${{ secrets.DOCKER_USERNAME }} make docker_push