name: GitHub Actions CI/CD
run-name: Build and Push Image to E2E-CR.
on:
  push:
    branches:
      - e2e-infra-automation

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: registry.e2enetworks.net
          username: ${{ secrets.E2E_USERNAME }}
          password: ${{ secrets.E2E_PASSWORD }}

      - name: Get Hash
        id: get_commit_hash
        run: echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
      
      - name: Build and push docker image to E2E-CR.
        env:
          REGISTRY: registry.e2enetworks.net
          REPOSITORY: poc-e2e-registry
          IMAGE_TAG: ${{ env.git_hash }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

          