name: GitHub Actions CI/CD
run-name: Build and Push Image to E2E-CR.
on:
  push:
    branches:
      - e2e-infra-automation
    paths-ignore:
     - 'helmcharts/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: registry.e2enetworks.net
          username: ${{ secrets.E2E_USERNAME }}
          password: ${{ secrets.E2E_PASSWORD }}

      - name: Get Hash
        id: get_commit_hash
        run: echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
      
      - name: Build and push docker image to E2E-CR.
        env:
          REGISTRY: registry.e2enetworks.net/poc-e2e-registry
          REPOSITORY: poc-e2e-registry
          IMAGE_TAG: ${{ env.git_hash }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

  CD:
      name: argocd-application
      needs: build-and-push
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout code 
          uses: actions/checkout@v3
          with:
                ssh-private-key: ${{ secrets.SSH_KEY }}
        - name: Get Hash
          id: get_commit_hash
          run: echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV

        - name: Git checkout branch
          run: |
              git status
              git checkout e2e-infra-automation

        - name: Update value.yaml file.
          run: sed -i "s/tag:.*/tag:\ ${{ env.git_hash }}/g" helmcharts/values.yaml
        
        - name: git commit and push values.yaml
          env:
            git_username: ${{ secrets.USER_EMAIL }}
            git_password: ${{ secrets.USER_PWD }}
          run: |
              git config --global user.email "$git_username"
              git config --global user.name "$git_password"
              git add helmcharts/values.yaml
              git commit -m "updated values in helm"
              git push --set-upstream origin e2e-infra-automation