name: GitHub Actions CI/CD
run-name: Deploying Local CI.
on:
  push:
    branches:
      - exercise-05
jobs:
  CI:
    runs-on: self-hosted
    steps:
      - run: echo "The job was automatically triggered by a Push event."
     