name: GitHub Actions CI/CD
run-name: Deploying Local CI.
on:
  push:
    branches:
      - exercise-04
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a Push event."
     
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Building flask application.
        run: |
          make flaskapp_build

      - name: Run docker compose.
        run: |
          make start-db

      - name: Push the Image into dockerHub.
        run: |
          make docker_push
        env:
          REPO_NAME: aashirathore111