name: GitHub Actions.
run-name: Deploying Local CD.
on:
  push:
    branches:
      - exercise-05
jobs:
  CD:
    runs-on: self-hosted
    steps:
      - run: echo "The job was automatically triggered by a Push event."
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up SSH key and Trigger deployment.
        env:
          VAGRANT_SSH_KEY: ${{ secrets.VAGRANT_SSH_KEY }}
        run: |
          echo "$VAGRANT_SSH_KEY" | tr -d '\r' > id_rsa
          chmod 0400 id_rsa
          ssh-add id_rsa
          scp -i id_rsa -P 2222 docker-compose-prod.yml vagrant@127.0.0.1:/home/vagrant
          ssh -i id_rsa -p 2222 vagrant@127.0.0.1 "sudo docker compose -f docker-compose-prod.yml up -d"