name: GitHub Actions CI/CD
run-name: Deploying Local CI and Local CD.
on:
  push:
    branches:
      - exercise-04
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a Push event."
     
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run flask application.
        run: |
          make flaskapp_build
      - name: Run docker compose
        run: |
          make docker_build